### ISSUE TITLE
Screenshots?

### ISSUE THREAD

**Issue by hedii** [bestmomo/nice-artisan#1]
Hi @bestmomo 
Some screenshots would be nice to see how your package looks like without having to install laravel.

**Comment by bestmomo** [comment]
You're right, here are some screenshots :

![nice-artisan1](https://cloud.githubusercontent.com/assets/2959682/11610549/a9a3055c-9ba6-11e5-936b-f1d3830baf62.jpg)
![nice-artisan2](https://cloud.githubusercontent.com/assets/2959682/11610548/a9a308e0-9ba6-11e5-9cee-94d7cc373024.jpg)
![nice-artisan3](https://cloud.githubusercontent.com/assets/2959682/11610547/a9a00942-9ba6-11e5-88b6-9c30f25f220f.jpg)

**Comment by hedii** [comment]
cool, thanks :)
