### ISSUE TITLE
Nothing to publish for tag [niceartisan:config]. (??)

### ISSUE THREAD

**Issue by SparrowDevPro** [bestmomo/nice-artisan#17]
Bonjour,
Pour commencer merci pour votre contribution et votre merveilleux cour sur le site du zero.
Je débute avec Laravel et j'essaye d'installer votre package mais j'ai l'erreur suivante dans ma console : 

E:\wamp64\www\BDHELARAVEL52>php artisan vendor:publish --tag=niceartisan:config
Nothing to publish for tag [niceartisan:config].

Mon .json : 
{
    "name": "laravel/laravel",
    "description": "The Laravel Framework.",
    "keywords": ["framework", "laravel"],
    "license": "MIT",
    "type": "project",
    "require": {
        "php": ">=5.5.9",
        "laravel/framework": "5.2.*",
		"laravelcollective/html": "5.2.*",
        "bestmomo/nice-artisan": "0.4.*"
    },

J'ai bien ajouté Bestmomo\NiceArtisan\NiceArtisanServiceProvider::class, dans mon fichier app.php.

Et quand j'essaye d'atteindre nice-artisan : 
ErrorException in NiceArtisanController.php line 94: array_keys() expects parameter 1 to be array, null given

Pourriez vous m'aider à résoudre le problème s'il vous plait ?

Je vous remercie par avance

**Comment by bestmomo** [comment]
Bonjour,

Je pense que j'ai ajouté le tag après la version 0.4

Pourquoi utiliser encore Laravel 5.2 ? Une raison spéciale ?

Pour publier la config il faut alors utiliser : **php artisan vendor:publish**

**Comment by SparrowDevPro** [comment]
Bonjour,
Je vous remercie pour votre réponse.
La raison pour laquelle j'utilise Laravel 5.2 est que l’hébergeur du site web (obambu) utilise encore une vieille version de PHP... C'est dommage mais je n'ai donc pas le choix.

**Comment by bestmomo** [comment]
Ah c'est dommage çà...

Je ne connaissais pas cet hébergeur, il a des tarifs très attrayants, mais apparemment quelques limitations...
