### ISSUE TITLE
argument default value

### ISSUE THREAD

**Issue by ffogarasi** [bestmomo/nice-artisan#2]
In 0.3 and 0.4.0 in the index.blade.php view  there is no check if the default value of the argument is array or string.
This is fixed in version 0.4.1.
As there are no other changes could you back port this in those versions?

**Comment by bestmomo** [comment]
As I have only 1 branch how could I change this version ?

**Comment by ffogarasi** [comment]
Yes you are right.
I made a fork of the project and will create separate branches for laravel 5.1 and 5.2 so I can refere to them in composer.
