### ISSUE TITLE
Class 'AppController' not found

### ISSUE THREAD

**Issue by marwein** [bestmomo/nice-artisan#3]
Hello Mr Maurice, nice job but still have some errors, and if i don't want to touch the vendor's code, i don't see how to resolve this issue,
the NiceArtisanController extends the AppController . but where is this AppController, i don't see it in L5.2 
How can i solve this problem ;-)

**Comment by bestmomo** [comment]
Hello,
**AppController** is an alias, look at **NiceArtisanServiceProvider**:
`AliasLoader::getInstance()->alias('AppController', $nameSpace . 'Http\Controllers\Controller');`

**Comment by haidaraKarara** [comment]
Bonjour,
Besoin d'aide.
A la deuxième étape pour installer nice-artisant, j'ai une erreur de ce type:
commande: 

C:\xampp\htdocs\laravel5>php artisan vendor:publish --provider="Bestmomo\NiceArtisan\NiceArtis
anServiceProvider::class"

Erreur générée: 
Nothing to publish for tag [].

Comment rétablir cela ?

**Comment by bestmomo** [comment]
Bonjour,
Oui j'ai vérifié il y a un souci, on peut s'en sortir avec seulement **php artisan vendor:publish** mais alors on va publier tous les packages, ce qui est dommage. Apparemment la commande a changé avec la version 5.3

**Comment by bestmomo** [comment]
Finalement j'ai ajouté un tag pour la publication, il suffit de faire un update du package et d'utiliser la commande :
`php artisan vendor:publish --tag=niceartisan:config`
Comme ça il n'y aura que ce config qui passera.

**Comment by haidaraKarara** [comment]
Bonjour,
oui même avec la nouvelle syntaxe ça bloque toujours. Peut être que c'est un problème de version.
Maintenant il génère cette erreur: 
Nothing to publish for tag [niceartisan:config]..
Mais bon c'est pas grave. Je suis habitué à la console quand même.
Je voulais tenter le coup car je suis nouveau sous laravel. C'est pour cela que j'explore tout ce que tu parle au niveau de ton cours.
Maintenant j'en suis à l'envoi des mails mais j'y arrive pas.

**Comment by bestmomo** [comment]
Je pense qu'il suffit de réinstaller le package pour avoir la dernière version en modifiant dans composer.json :
`"bestmomo/nice-artisan": 0.5.*`
Et ensuite lancer un :
`composer update`
Je pense qu'ensuite la commande de publication va fonctionner.
