### ISSUE TITLE
respecting config

### ISSUE THREAD

**Issue by ftrotter** [bestmomo/nice-artisan#9]
Tried to add console commands from another package. And it does not work.

Tried to remove entire sections of the configuration file and it does not work. 

Why have a configuration file if you are not going to change what is available in the UX by using your configuration file. 

color me confused.

-FT

**Comment by bestmomo** [comment]
I use `Artisan::all()` to get all commands but this method doesn't load custom packages commands. The config is only to manage tabs with recovered commands.

As this is a mix with symfony and Laravel I dont know how to get also custom packages commands...

**Comment by ftrotter** [comment]
Thank you for the response... closing issue!!
